### ISSUE TITLE
Latest changes aren't published

### ISSUE THREAD

**Issue by spk83** [andrewrothstein/ansible-supervisord#6]
Could you please tag and publish latest commit when you get chance? Thanks!

**Comment by andrewrothstein** [comment]
published as v2.0.0. I migrated to using miniconda to better isolate the required python version (2.4+) from the underlying os python version choice.

**Comment by spk83** [comment]
@andrewrothstein could you please tag/publish latest commit when you get chance? Thanks!

**Comment by andrewrothstein** [comment]
published v2.0.3 to the galaxy
